/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/michele/catkin_ws/devel/share/behavior_trees/msg/ROSGoal.msg
 *
 */


#ifndef BEHAVIOR_TREES_MESSAGE_ROSGOAL_H
#define BEHAVIOR_TREES_MESSAGE_ROSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_trees
{
template <class ContainerAllocator>
struct ROSGoal_
{
  typedef ROSGoal_<ContainerAllocator> Type;

  ROSGoal_()
    : GOAL_(0)  {
    }
  ROSGoal_(const ContainerAllocator& _alloc)
    : GOAL_(0)  {
    }



   typedef int32_t _GOAL__type;
  _GOAL__type GOAL_;




  typedef boost::shared_ptr< ::behavior_trees::ROSGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_trees::ROSGoal_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ROSGoal_

typedef ::behavior_trees::ROSGoal_<std::allocator<void> > ROSGoal;

typedef boost::shared_ptr< ::behavior_trees::ROSGoal > ROSGoalPtr;
typedef boost::shared_ptr< ::behavior_trees::ROSGoal const> ROSGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_trees::ROSGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_trees::ROSGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace behavior_trees

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'behavior_trees': ['/home/michele/catkin_ws/devel/share/behavior_trees/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::behavior_trees::ROSGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_trees::ROSGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_trees::ROSGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_trees::ROSGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_trees::ROSGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_trees::ROSGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_trees::ROSGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7b14ba257795c9c39554f76f2fa8ca0";
  }

  static const char* value(const ::behavior_trees::ROSGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7b14ba257795c9cULL;
  static const uint64_t static_value2 = 0x39554f76f2fa8ca0ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_trees::ROSGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_trees/ROSGoal";
  }

  static const char* value(const ::behavior_trees::ROSGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_trees::ROSGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
int32 GOAL_\n\
";
  }

  static const char* value(const ::behavior_trees::ROSGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_trees::ROSGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.GOAL_);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ROSGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_trees::ROSGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_trees::ROSGoal_<ContainerAllocator>& v)
  {
    s << indent << "GOAL_: ";
    Printer<int32_t>::stream(s, indent + "  ", v.GOAL_);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_TREES_MESSAGE_ROSGOAL_H
